### ISSUE TITLE
NoMethodError: undefined method `check_delivery_params' for #<Mailgunner::DeliveryMethod:0x00560ebde6ad08>

### ISSUE THREAD

**Issue by brian626** [timcraft/mailgunner#13]
The most recent version of `mail` (2.6.6) appears to have changed the semantics of `Mail::CheckDeliveryParams` in this commit: https://github.com/mikel/mail/commit/37908c37dfb26ea262d0fa7916cd9bbee3750e63

I believe the fix is to remove `include Mail::CheckDeliveryParams` from `lib/mailgunner/delivery_method.rb` and change `check_delivery_params(mail)` to `Mail::CheckDeliveryParams.check(mail)`.

**Comment by JohnnyDevv** [comment]
I have done as you instructed sir, but i still get the same errors

**Comment by brian626** [comment]
A workaround is to revert to version 2.6.5 of `mail` until this gem is updated.

**Comment by JohnnyDevv** [comment]
So what gem do I need to install

**Comment by brian626** [comment]
`mail` is already installed as a requirement of `actionmailer`, so you just need to specify a version by adding this to your `Gemfile`:

    gem 'mail', '2.6.5'

**Comment by JohnnyDevv** [comment]
Does it work well in production?

**Comment by brian626** [comment]
I've been using it in production since I opened this issue with no problems.

**Comment by timcraft** [comment]
Looks to be a correct assessment of the problem/fix, good of them to break backwards compatibility in a patch level version. Workaround for now is pinning your mail dependency to 2.6.5 or lower as you suggest. I'll get around to updating to the new interface in due course.

(Backwards compatible pull requests welcome.)

**Comment by timcraft** [comment]
Fixed in 70272cd (available in v2.5.0)

@brian626 Thanks for the heads up!
