### ISSUE TITLE
RuntimeError: Invalid delivery method :mailgun

### ISSUE THREAD

**Issue by th3m4ri0** [timcraft/mailgunner#8]
I get the ```RuntimeError: Invalid delivery method :mailgun``` error when using this gem on Heroku.

**Comment by subicura** [comment]
:+1: me too

**Comment by timcraft** [comment]
@th3m4ri0 @subicura Can you try version 2.2.1 and see if that fixes it please.

**Comment by subicura** [comment]
@timcraft It works! Thank you!!

**Comment by pjscopeland** [comment]
I get the above error when using version 2.2.1. I don't get it in `production`, but I do get it in `uat`, which uses identical configuration (in fact, the config file is a symlink).

**Comment by pjscopeland** [comment]
Oh, I think I know why... mailgunner probably needs to be in the :uat group in my Gemfile...
